### ISSUE TITLE
Meaningful description?

### ISSUE THREAD

**Issue by ivanakimov** [raviqqe/muffet#10]
I just starred on Github, and I know when I'll need this later, I won't be able to find it. Can you put "link checker" or something meaningful in the description / tags of the repo? Awesome project btw!

**Comment by raviqqe** [comment]
Sorry, I was just joking there. Does "Fast website link checker in Go" sound good for you?

**Comment by ivanakimov** [comment]
Yeah, shows up in my results now 😄 Thanks!
