### ISSUE TITLE
support http?

### ISSUE THREAD

**Issue by kybin** [raviqqe/muffet#11]
Thank you @raviqqe . It looks simple and useful.

I checked a http site with muffet.

It works on index page. But it changes the site's links to https.

So it does not found the linked pages.

Do you have plan to add support of http sites?

**Comment by raviqqe** [comment]
Can you put the link to the website here so that the bug can be reproduced?

**Comment by kybin** [comment]
I find my mistake. 

I assume it will print OK for valid link. It seems I should put `-v` flag for that.

Sorry for the confusion!
