### ISSUE TITLE
--json does not respect -v

### ISSUE THREAD

**Issue by Joshfindit** [raviqqe/muffet#128]
Verions: `2.2.1`
To reproduce: `muffet -v --json <url>`

**Comment by raviqqe** [comment]
It's expected behaviour in the current implementation as described in #43. Do you think it's just confusing or do you actually want successful results to be included too?

**Comment by Joshfindit** [comment]
@raviqqe Confusing.

Normally when I use a command-line tool, I expect that the output is the output, and that if there’s a flag to change the output format, that all expected output will be converted to that format (if that makes sense).

In this case, I would expect that “-v” and “—json -v” would output the same verbose entries, just in the different formats.
