### ISSUE TITLE
github.com/raviqqe/muffet/v2 is 404

### ISSUE THREAD

**Issue by Joshfindit** [raviqqe/muffet#130]
README install instructions show `GO111MODULE=on go get -u github.com/raviqqe/muffet/v2`, but github.com/raviqqe/muffet/v2 does not currently exist

**Comment by raviqqe** [comment]
Can you try with the latest Go?

**Comment by Joshfindit** [comment]
I can double-check if you like, I don’t have access to the machine right now but it was a Digital Ocean Ubuntu droplet using `apt install golang` directly before `go get`.

Two things to note:
1. https://github.com/raviqqe/muffet/v2 gives 404
2. Doing `go get -u github.com/raviqqe/muffet` worked fine to get v2.2.2

**Comment by Joshfindit** [comment]
Confirmed:
The version on the droplet where it does not work is `go1.10.4 linux/amd64`,
and doing `GO111MODULE=on go get -u github.com/raviqqe/muffet/v2` from `go1.15.2 darwin/amd64` *does* work
