### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by KieranHunt** [raviqqe/muffet#133]
Hey!

Very cool tool. ✨ 

Have you considered distributing through Homebrew?

I try to grab most things from there where possible.

**Comment by chenrui333** [comment]
👋  just heads up, I have created a formula on the homebrew-core for this awesome utility.

**Comment by raviqqe** [comment]
@chenrui333 Thank you so much! Let me know if you need any work from my side!

**Comment by raviqqe** [comment]
It's merged into Homebrew! Thank you for your contribution, everyone!

**Comment by chenrui333** [comment]
yeah, I forgot to mention in here, yeah, it got merged. 🎉
