### ISSUE TITLE
Needs proxy support

### ISSUE THREAD

**Issue by dushmis** [raviqqe/muffet#17]
Current version doesn't work behind proxy

**Comment by raviqqe** [comment]
Is the problem you are facing as same as #19?

**Comment by dushmis** [comment]
in my case it just fails with error
`dialing to the given TCP address timed out`

**Comment by raviqqe** [comment]
Can you try `curl` or something to access the URL? Or, if it may be because of too much IO on your local machine, can you try `--concurrency` option to reduce numbers of concurrent connections?

**Comment by dushmis** [comment]
i am behind corporate proxy, it doesn't work behind proxy it works fine on the internet.
curl works fine with -x ( for proxy of course )

**Comment by okonomiyaki3000** [comment]
^Same

**Comment by raviqqe** [comment]
I'm really eager to support HTTP proxies but still figuring out how to use them with `fasthttp` as it's mentioned in valyala/fasthttp#168.
