### ISSUE TITLE
Virustotal marks win binary 2.4.4 as malicious

### ISSUE THREAD

**Issue by c33s** [raviqqe/muffet#187]
`muffet_2.4.4_Windows_x86_64.tar.gz`:
- Microsoft: Trojan:Win32/Wacatac.B!ml
https://www.virustotal.com/gui/file/d7051a2d9a5e58f7167899fe692fc654114ed888e11d134b5067553442ea6159?nocache=1

`muffet.exe`:
- MaxSecure: Trojan.Malware.300983.susgen
- SecureAge APEX: Malicious
https://www.virustotal.com/gui/file/364d6ce0938e039c27f9d6d83b1c46f4210019e2add02c8cf1c4ddef1cb0533d?nocache=1

`https://github.com/raviqqe/muffet/releases/download/v2.4.4/muffet_2.4.4_Windows_x86_64.tar.gz`:
- clean
https://www.virustotal.com/gui/url/29d46515ae255bca5501c77f18d8d9146f32a1cacc8000a4636c8fcc8f97dd97?nocache=1

**Comment by c33s** [comment]
windows x32 builds are ok except for SecureAge APEX which happens quite often as they use AI

**Comment by raviqqe** [comment]
Actually, even the v1.1.0 binary is detected as Trojan. Maybe because it does random network access? More investigation is needed...

https://www.virustotal.com/gui/file/2bfaa0425644629feeb9a4e0d0a7c0632a06ffc5c72036e035f4ee8221b65855?nocache=1

**Comment by raviqqe** [comment]
This seems to be more like a false positive of the security software and Muffet is not detected malicious by other major ones like Windows Defender.

So I'm closing this for now. Let me know if this affects your workflow significantly!
