### ISSUE TITLE
Links on redirected subdomain pages aren't handled properly

### ISSUE THREAD

**Issue by hermansc** [raviqqe/muffet#20]
Say I have a 301 redirect on my site example.org:

`example.org/foo/bar -> zoo.example.org/haz`

Now on this site I have a `href="/somewhere"`, the tool reports 404 because it can't find:

`example.org/somewhere`, which of course it can't because the `/somewhere` page is on the `zoo` subdomain.

**Comment by raviqqe** [comment]
Merged changes to fix the wrong behavior on redirected URL resolutions into master. Could you test the latest version of `muffet` with your website?

**Comment by raviqqe** [comment]
Closing as the problem seems to be fixed.
