### ISSUE TITLE
Create a Dockerfile to execute

### ISSUE THREAD

**Issue by rodolphopivetta** [raviqqe/muffet#21]
A valid way to execute the application is containerised, and share the docker image on Docker Hub will be great

**Comment by raviqqe** [comment]
Can you raise some use cases for that? I think `go get` is just enough as `muffet` is not something like servers but just a command and doesn't depend on any external libraries.

**Comment by rodolphopivetta** [comment]
I did not want to install Go on my OS for example, and I wanted to test the project. Is just an alternative to run.

Another use case is to put the `muffet` as a job in my CI pipeline to test a web application.

**Comment by rodolphopivetta** [comment]
Thanks

**Comment by raviqqe** [comment]
I just uploaded Docker image to the hub. Here is [the link](https://hub.docker.com/r/raviqqe/muffet).
