### ISSUE TITLE
Fragments on github md.

### ISSUE THREAD

**Issue by lahabana** [raviqqe/muffet#219]
The way GH generates anchors in for markdown files gives the html (for: https://github.com/spiffe/spiffe/blob/main/standards/X509-SVID.md#41-basic-constraints): 

```html
<a id="user-content-41-basic-constraints" class="anchor" aria-hidden="true" href="#41-basic-constraints">
...
</a>
```

Seems a little related to #52 though I'm unsure if Github achieves anchors with JS or this type of `<a>` is regular html.

**Comment by raviqqe** [comment]
This seems to be rather because JS in the page handles fragments of section links manually by converting them (e.g. `#4.1.-basic-constraints`) to real ones (e.g. `#user-content-41-basic-constraints`). So for the same reason as #52, we can't support this right now.
