### ISSUE TITLE
Install error?

### ISSUE THREAD

**Issue by ashbyca** [raviqqe/muffet#24]
When trying to install I receive the following error:

$ go get -u github.com/raviqqe/muffet
# github.com/raviqqe/muffet
go/src/github.com/raviqqe/muffet/fetcher.go:17: undefined: sync.Map

Any suggestions, sorry this is my first go around with go...

**Comment by ashbyca** [comment]
Sorry this is on an ubuntu 16.04 LTS (4.13.0-1012-gcp) host.

**Comment by raviqqe** [comment]
It's just a Go version issue. Please update Go to the newer version.

**Comment by eparra** [comment]
I upgraded to Go 1.10.1 and everything worked fine.
