### ISSUE TITLE
404 on link with double slashes

### ISSUE THREAD

**Issue by philrz** [raviqqe/muffet#240]
Consider the following `index.html`:

```
<a href="https://static.googleusercontent.com/media/research.google.com/en//archive/mapreduce-osdi04.pdf">MapReduce paper</a>
```

When I serve this and run `muffet` against it, it gives a 404.

```
$ python3 -m http.server
Serving HTTP on :: port 8000 (http://[::]:8000/) ...
```

```
$ muffet http://localhost:8000/index.html
http://localhost:8000/index.html
	404	https://static.googleusercontent.com/media/research.google.com/en//archive/mapreduce-osdi04.pdf
```

I suspect the double slash `//` is what's causing the problem, and that `muffet` may be turning it into a single slash before following the link. Unfortunately the site truly wants to only return the doc from that URL with double slash. Chrome and `curl` both return the doc from this double-slashy URL without complaint.

I did some web searches that say that such URLs are bad form, but strictly speaking, they're legal.

**Comment by raviqqe** [comment]
Actually, this normalization seems to be done by the `fasthttp` library.

```go
func TestDoubleSlash(t *testing.T) {                                                                 
        s := "https://static.googleusercontent.com/media/research.google.com/en//archive/mapreduce-osdi04.pdf"
        r, err := http.Get(s)   

        assert.Nil(t, err)
        assert.Equal(t, 200, r.StatusCode)

        c, _, err := fasthttp.Get(nil, s)

        assert.Equal(t, 404, c)                                                                      
}
```
