### ISSUE TITLE
Feature: Support metadata URLs used for open graph/twitter cards

### ISSUE THREAD

**Issue by azeemba** [raviqqe/muffet#268]
Websites can provide metadata like thumbnails/preview images using the `<meta>` tag. [Open Graph](https://ogp.me/) is used by most platforms and Twitter has its own format but they all use `<meta>` tags where the `content=` attribute can contain a URL.

My use case is that I crawl my website locally to make sure that I don't have any broken links in the meta URLs. So I would find this feature helpful.

I am happy to send a PR but wanted to check if there is interest in this feature first.

**Comment by raviqqe** [comment]
Sounds good to me!

One concern is that the `<meta />` tags' `content` property can mean anything depending on their attributes. OpenGraph is a kind of defacto standard but I believe there are also similar tags for Twitter. I hope supporting `meta` tags doesn't bloat the feature and maintenance burden in the future. 😅

**Comment by azeemba** [comment]
The code change turned out to be pretty small but its definitely a valid concern. I will push a PR so you can share your thoughts
