### ISSUE TITLE
Links are scanned multiple times

### ISSUE THREAD

**Issue by csharmath** [raviqqe/muffet#27]
Pretty cool project, saw it on hackers news!

Just for fun try to run it against https://msdn.microsoft.com ( they are notorious to have broken links all over the place ).

example from the result showing duplicates ( there are many)
OK      https://www.visualstudio.com
OK      https://www.visualstudio.com/
OK      https://www.visualstudio.com/
OK      https://www.visualstudio.com/

**Comment by raviqqe** [comment]
I'm not sure if results outputs must be normalized or not as we haven't decided what kinds of information should be included there yet as it is mentioned in #16.

**Comment by csharmath** [comment]
So it's only scanned once, but printed as many times it sees it ?

**Comment by raviqqe** [comment]
Yes, exactly. The results are cached in a best effort way using `sync.Map`.

**Comment by csharmath** [comment]
thanks for answering!
Personally I was curious to see the unique list of url's, so perhaps that could be considered as an option ?
alternatively, I can post-process the results of course...
But now just thinking, if you print the occurrences, then stats could also be interesting :)

**Comment by raviqqe** [comment]
Or are you talking about duplicate result outputs of the same URLs over multiple pages?

**Comment by raviqqe** [comment]
Closed by 5826483.
