### ISSUE TITLE
Memory leak on Windows 10

### ISSUE THREAD

**Issue by CJHarmath** [raviqqe/muffet#28]
Not sure if it's platform specific or not, but when were running a scan for https://msdn.microsoft.com for fun as mentioned in #27 just noticed muffet.exe using ~7Gb of memory and kept going...

**Comment by raviqqe** [comment]
That seems to be because of the result caching feature of `muffet`. To reduce numbers of HTTP requests, `muffet` caches their results in a map data structure. So, memory usage grows until it finishes scraping all the pages in websites.

**Comment by raviqqe** [comment]
I tried `muffet` with the MSDN URL and the cause seems to be due to [unlimited spawns of goroutines](https://github.com/raviqqe/muffet/blob/fe547e37a05c6bc2b8a622fa73a46e3a13129f82/daemons.go#L24) to avoid dead lock associated with a channel holding all pages which need to be analyzed later.

**Comment by jtarchie** [comment]
Maybe channel doesn't ned to hold the lock, but the map can hold the lock.

**Comment by jtarchie** [comment]
Why would this be an unlimited spawn? The limit on the capacity is defaults to 512.

**Comment by raviqqe** [comment]
This issue is created for `muffet` v0 and I think it's solved already by its concurrency limit. Now the maximum memory usage should be bound by the sizes of websites `muffet` is running on.
