### ISSUE TITLE
unsplash.com returns 405

### ISSUE THREAD

**Issue by xoxys** [raviqqe/muffet#288]
A few days ago, checking `unsplash.com` URLs has stopped working and returns HTTP 405 now. Checking the sites with curl still seems to be working, any idea why this happens with muffet?

```
http://127.0.0.1:8000/posts/2020/07/create-a-static-site-hosting-platform/
	405	https://unsplash.com/@altumcode
	405	https://unsplash.com/s/photos/coding
```

**Comment by raviqqe** [comment]
Can you try masquerading a `user-agent` header like `--header 'user-agent: curl'`?

**Comment by xoxys** [comment]
Thanks.  Yes, that seems to work.
