### ISSUE TITLE
feature request: scan sitemap.xml

### ISSUE THREAD

**Issue by mdstaff** [raviqqe/muffet#32]
Hello,

I'm quite impressed by this project you have here!  I was wondering if it would be possible to use muffet to check links in a particular sitemap?

Cheers,
Matt

**Comment by raviqqe** [comment]
I think it is a nice idea as we should also support `robots.txt` to exclude some pages.

**Comment by raviqqe** [comment]
BTW, do you want `muffet` to scrape only pages listed in `sitemap.xml` or use it as roots of scraping?

**Comment by mdstaff** [comment]
I'm open to either but my intended use case was to catalog sitemap pages by server HTTP response code.

**Comment by raviqqe** [comment]
Closed by bd3ff3c and c9c713b.

**Comment by raviqqe** [comment]
Thx for your feature request!
