### ISSUE TITLE
Ability to add custom DNS servers

### ISSUE THREAD

**Issue by skngetich** [raviqqe/muffet#354]
I would like to add custom DNS servers before making the request.

Is this possible?

**Comment by raviqqe** [comment]
Can you describe more details of your situation?

**Comment by cloudemprise** [comment]
Adding the ability to specify custom DNS servers could be useful for muffet in certain scenarios. One potential benefit is that it would allow checking links that might be filtered or blacklisted by local DNS services, such as trackers or ad-related links. Running muffet with an unfiltered external DNS server could help ensure a more comprehensive link checking process. I'd be interested to hear other perspectives from the community on this proposal.

**Comment by craigreyenga** [comment]
I think something like that could be achieved by pointing Muffet to a proxy server which itself uses those alternative DNS servers. But I like the idea still.
