### ISSUE TITLE
muffet treats preconnect hrefs like links

### ISSUE THREAD

**Issue by movitz-s** [raviqqe/muffet#391]
Websites often have code like this

```html
<link rel="preconnect" href="https://fonts.googleapis.com">
```
in order to increase performance. `https://fonts.googleapis.com` returns 404 but the HTML code is still valid and should not be checked by muffet. 

Is this a unknown issue or am I doing something wrong with muffet?  
I am willing to implement a fix for this, just lmk.

**Comment by raviqqe** [comment]
You can exclude certain links with `--exclude` option. Can you try it?

**Comment by raviqqe** [comment]
I see. If you can implement it, I appreciate it!
