### ISSUE TITLE
Error: "no free connections available to host"

### ISSUE THREAD

**Issue by planbnet** [raviqqe/muffet#41]
Many requests fail with "no free connections available to host", even if I specify -c1 on the command line. The error seems to come directly from fasthttp, but it looks like muffet is trying to create new connections before the previous ones have been closed completely.

**Comment by planbnet** [comment]
Same problem - on both a windows and a linux machine.
The problem might be that I'm scanning the local network, so connections are very fast. I can't rule out that this is caused by a problem with the local server I'm trying to scan, though I wouldn't expect this error message in that case...

**Comment by raviqqe** [comment]
How about `too many open files` errors? Do you see them at the same time?

**Comment by planbnet** [comment]
Nope, no such errors - not on the command line and not in any system logs...

Am Mi., 3. Okt. 2018 um 07:01 Uhr schrieb Yota Toyama <
notifications@github.com>:

**Comment by raviqqe** [comment]
This issue should be fixed on master.
