### ISSUE TITLE
Build docker image for arm64 architecture

### ISSUE THREAD

**Issue by themastersdev** [raviqqe/muffet#413]
I was playing around with this repo in a mac laptop with the M1 chip and could not use the docker image being pushed to docker hub because it is for the amd64 architecture. 

The docker image built with the `tools/docker.sh` does not support arm64. We can create a multi-platform build with the argument `--platform linux/arm64,linux/amd64` to support arm64 and amd64.

**Comment by raviqqe** [comment]
Closed by #417.
