### ISSUE TITLE
Named anchors

### ISSUE THREAD

**Issue by Naramsim** [raviqqe/muffet#42]
First of all, thanks for the amazing tool.

I noticed that `muffet` only supports anchors to HTML elements with an `id` attribute.

Consider that anchors also works on HTML elements with `name` attribute.

```html
<a name="Dependency_Scope" data-devgib="tagged">Dependency Scope</a>
```
Some examples:
- https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope
- https://docs.oracle.com/javase/tutorial/reflect/member/methodparameterreflection.html#implcit_and_synthetic
- https://docs.oracle.com/javase/specs/jls/se7/html/jls-3.html#jls-3.8
- (Jeah I know, those are all Java things)

**Comment by raviqqe** [comment]
I understand but the `name` attributes are a kind of obsolescent as it's not supported by HTML5. So, if someone want this feature for backwards compatibility or something, please 👍 on this issue.
