### ISSUE TITLE
Spaces are deleted from internal links (bookmarks)

### ISSUE THREAD

**Issue by ArtFlag** [raviqqe/muffet#44]
Hello and thanks fot this tool, it's been really useful! 

I encountered a small issue with `href` tags:

With the following HTML:
```html
<span id"this bookmark">foo</span>
<a href="#this bookmark">Click</a>
```
The checker returns `id thisbookmark not found`.  The space inside the `href` is deleted. 

Any chance of avoiding this deletion (or is it done by an HTML parsing lib you use?) 

Thanks!

**Comment by StephenBrown2** [comment]
`id`'s cannot contain spaces, so I believe it's simply making it a valid ref.
> When specified on HTML elements, the id attribute value must be unique amongst all the IDs in the element's tree and must contain at least one character. The value **must not contain any ASCII whitespace**.

Ref: https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute

**Comment by ArtFlag** [comment]
I realized that after my message, you're right 👍  

Thanks for your tool 🙂
