### ISSUE TITLE
Publish binary releases for easier usage

### ISSUE THREAD

**Issue by Calinou** [raviqqe/muffet#46]
Please consider uploading binary releases to GitHub Releases, so that people can quickly use this tool without installing a Go toolchain (which can be helpful in continuous integration). This is made easy thanks to tools like [GoReleaser](https://goreleaser.com/) :slightly_smiling_face:

**Comment by raviqqe** [comment]
Now we have automated releases for muffet. Thanks for your contribution!

**Comment by peaceiris** [comment]
@raviqqe Great! Thank you so much.
