### ISSUE TITLE
Add support to read input HTML from a directory

### ISSUE THREAD

**Issue by geeknoid** [raviqqe/muffet#50]
When producing a web site from a static site generator like Hugo, it'd be highly desirable to be able to verify the links in a statically generated site on disk. So basically:

- Instead of specifying a URL to fetch from, let me specify a file system directory

- Iterate through all the HTML files and analyze them.

- Provide a mappings layer to map the public location of the web site to the directory. So basically make it so https://foo/bar gets translated to mysite/bar.

I could then check the site's link before publishing.

I currently use htmlproofer for this task and it is awfully slow and it requires Ruby. Muffet seems like a much superior solution.

Thanks.

**Comment by ruzickap** [comment]
Hello guys.

I wrote a simple GitHub Action which is using muffet to check the HTML pages on the disk [https://github.com/ruzickap/action-my-broken-link-checker](https://github.com/ruzickap/action-my-broken-link-checker).

I also documented the way how to do the same using Docker (if you do not want to use it as GH Action).

You can give it a try if you are still interested...

**Comment by raviqqe** [comment]
I think this is out of the scope of this project because we cannot guarantee that links work without using specific HTTP servers. For example, some servers add trailing slashes automatically but the others don't (e.g. `foo/bar` -> `foo/bar/`.)

So I'm closing this issue for now but feel free to reopen this if you have different opinions!

**Comment by asbjornu** [comment]
Seeing how both [HTMLProofer](https://github.com/gjtorikian/html-proofer) and [htmltest](https://github.com/wjdp/htmltest) supports local file checking, I'd say it's a feature that safely could be defined as in scope for Muffet. Of the two, HTMLProofer is the most feature-rich and supports variable end slashes as well as optional `.html` extensions. I believe that's all that is required for being able to robustly check a local folder of HTML files.
