### ISSUE TITLE
Repeated link checks and zillions of timeouts

### ISSUE THREAD

**Issue by geeknoid** [raviqqe/muffet#51]
I just tried:

muffet --timeout 60 https://istio.io 

The result is 8000 lines of output indicating that a great many pages experienced timeout errors. Any given page is shown a great many times in the output, which seems to indicate it is being processed multiple times (I would expect any given link to be visited only once during a given scan).

When I use the -v option, The output grows to at least 50000 lines, and this time both page that time out and pages that don't time out appear multiple times in the output.

So the first problem is the fact the same pages seem to be visited multiple times.

The second problem are these timeouts. I gave it 60 second timeout intervals, and I don't believe that our CDN is unable to deliver the desired content in 60 seconds for so many pages. When accessing the links from a browser, they appear instantaneously.

I change my command-line to:

muffet -c 32 --timeout 10 https://istio.io 

This eliminated all the timeout errors. So the problem is on my side, and not on the CDN. I'm running this on a Mac, perhaps it has some limits to the number of opened sockets (or something similar) which is being interpreted as timeouts by the link checker. So it might be good to dynamically discover the problem and tune down the concurrency accordingly.

**Comment by ijt** [comment]
I'm seeing the same problem with spurious timeouts, also on a Mac.

**Comment by raviqqe** [comment]
For duplicate link checks, please see #38.

**Comment by raviqqe** [comment]
I increased the default TCP timeout to 1 minute. Let me know if you still have issues!
