### ISSUE TITLE
Feature Request: Colors

### ISSUE THREAD

**Issue by ruzickap** [raviqqe/muffet#61]
Hello.

Would it be possible to implement parameter which will disable/enable colors in muffet ?

Something like:

```
-C, --color <auto | always | never>    Use color [default: auto]
```

It will help on some "dumb" terminals to "force" color or just disable it completely.

**Comment by raviqqe** [comment]
Do you think just `--no-color` option would cover all the use cases?

**Comment by ruzickap** [comment]
Partially. Sometimes it's also handy to "force colors" when - thats why I mentioned the "color possibilities" above.

I took this example from [grep](https://www.gnu.org/software/grep/manual/grep.html).
