### ISSUE TITLE
Feature request: report error on links to redirects

### ISSUE THREAD

**Issue by brandon-rhodes** [raviqqe/muffet#65]
I'm enjoying the performance of this tool! But, to improve user experience of the web and lower server costs, I like linking directly to the current URL for a page instead of linking to an old URL that is simply a redirect.

Could an option be added that would report all URLs leading to redirects as broken instead of valid? I tried `-l 0` to turn redirection-following off, but muffet still seems to follow at least a single initial redirection.

**Comment by raviqqe** [comment]
Do you still have this problem? `-l 0` seems to work for me.

**Comment by brandon-rhodes** [comment]
I just upgraded, and it now seems to work perfectly! Thank you, I'll close this issue now.
