### ISSUE TITLE
Spaces removed from links (all URLs)

### ISSUE THREAD

**Issue by StephenBrown2** [raviqqe/muffet#72]
Related to #44, however, now I've come across a site (being published on Read the Docs) which has many spaces in the filenames. Though the IDs are fine, the spaces get removed from the path, which breaks the links and results in many false 404's.

Perhaps instead of removing spaces, using the `net/url` Parse function only? Or removing spaces only from the `URL.Fragment`?
https://github.com/raviqqe/muffet/blob/4998c9b377f664bcad596990afeac7679cb306c8/scraper.go#L48-L54
https://github.com/raviqqe/muffet/blob/4998c9b377f664bcad596990afeac7679cb306c8/scraper.go#L82-L90
https://play.golang.org/p/42kUw1Rg23m

**Comment by raviqqe** [comment]
https://tools.ietf.org/html/rfc3986

Actually the URI spec says that those spaces should be ignored. Do those Read the Docs pages work well on browsers?

**Comment by StephenBrown2** [comment]
Yes, here are a few examples:
Running on https://draft-openaps-reorg.readthedocs.io/en/reapply-cleanup/ gives many 404's for URLs such as:
- 404 URL
  - Actual URL with spaces (200)
- https://draft-openaps-reorg.readthedocs.io/en/reapply-cleanup/docs/BuildYourRig/install-overview.html
  - https://draft-openaps-reorg.readthedocs.io/en/reapply-cleanup/docs/Build%20Your%20Rig/install-overview.html
- https://draft-openaps-reorg.readthedocs.io/en/reapply-cleanup/docs/Customize-Iterate/iPhoneShortcutsIntegration.html
  - https://draft-openaps-reorg.readthedocs.io/en/reapply-cleanup/docs/Customize-Iterate/iPhone%20Shortcuts%20Integration.html
- https://draft-openaps-reorg.readthedocs.io/en/reapply-cleanup/docs/GearUp/CGM.html
  - https://draft-openaps-reorg.readthedocs.io/en/reapply-cleanup/docs/Gear%20Up/CGM.html
- https://draft-openaps-reorg.readthedocs.io/en/reapply-cleanup/docs/GiveBack-PayItForward/contribute.html
  - https://draft-openaps-reorg.readthedocs.io/en/reapply-cleanup/docs/Give%20Back-Pay%20It%20Forward/contribute.html
- https://draft-openaps-reorg.readthedocs.io/en/reapply-cleanup/docs/Howitworks/autosens.html
  - https://draft-openaps-reorg.readthedocs.io/en/reapply-cleanup/docs/How%20it%20works/autosens.html
- https://draft-openaps-reorg.readthedocs.io/en/reapply-cleanup/docs/UnderstandingOpenAPS-Overview/communication-support-channels.html
  - https://draft-openaps-reorg.readthedocs.io/en/reapply-cleanup/docs/Understanding%20OpenAPS-Overview/communication-support-channels.html
- https://draft-openaps-reorg.readthedocs.io/en/reapply-cleanup/docs/Usageandmaintenance/Wifi/bluetooth-tethering-edison.html
  - https://draft-openaps-reorg.readthedocs.io/en/reapply-cleanup/docs/Usage%20and%20maintenance/Wifi/bluetooth-tethering-edison.html
- https://draft-openaps-reorg.readthedocs.io/en/reapply-cleanup/docs/WhileYouWaitForGear/collect-data-and-prepare.html
  - https://draft-openaps-reorg.readthedocs.io/en/reapply-cleanup/docs/While%20You%20Wait%20For%20Gear/collect-data-and-prepare.html

**Comment by raviqqe** [comment]
I see your point. I will change the behaviour of `muffet` then because I think people expect `muffet` to work similar to browsers..

But I still don't understand the spec of URLs and HTML actually. The both `foo` and `bar` links of encoded and decoded URLs in the following HTML works on Chrome while the spec says the `href` attributes are always valid URLs after their leading and trailing spaces are stripped.

`index.html`:

```html
<html>
  <body>
    <a href="/a b.html">foo</a>
    <a href="/a%20b.html">bar</a>
  </body>
</html>
```

`a b.html`:

```html
<html>
  <body>
    <a href="/">back</a>
  </body>
</html>
```

Am I missing something???

Anyway, thanks for the report!

**Comment by StephenBrown2** [comment]
Ah, I think I know where the misunderstanding comes from:
> the spec says the href attributes are always valid URLs after their **leading and trailing** spaces are stripped.

Leading and trailing spaces should most certainly be stripped, however, _internal_ spaces should not, and instead be URI-encoded (percent-encoded). So, `strings.TrimSpace` is the right way to go about it, if just working with strings, but why not use https://golang.org/pkg/net/url/#Parse directly?

**Comment by raviqqe** [comment]
I did `TrimpSpace` because I wanted to strip spaces even on URL parse errors anyway. But it might be simpler to do `url.Parse` first. Thanks for the feedback!

**Comment by StephenBrown2** [comment]
No worries. It works well as is, just trying to be helpful as I learn more Go myself!
