### ISSUE TITLE
Doesn't support links with hashes

### ISSUE THREAD

**Issue by tmcw** [raviqqe/muffet#9]
Testing this tool with my website gives a lot of great information (thanks!) but runs into a few issues, of them being a link like:

    https://en.wikipedia.org/wiki/Bell_Labs#1970s

It reports this link to be a 400, I would guess because it's sending the full URL to the server instead of requesting the portion

    https://en.wikipedia.org/wiki/Bell_Labs

That a web browser or other client would request, because the `#1970s` portion is not part of the server request path.

**Comment by raviqqe** [comment]
Thank you for your feedback and you're right. My website's hosting service handled that kind of corrupted URLs well somehow. The correct approach would be fetching pages with modified URLs and finding elements with correct IDs.

**Comment by gtirloni** [comment]
Another variation that's handled by WordPress well is: https://example.com/page/#Something

**Comment by bensooter** [comment]
Similar issue with links like this to pull things like fonts, returns an '(invalid status code 400)'
`<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:100, 200,300,400,500,700,400italic">`

**Comment by raviqqe** [comment]
I just committed changes to fix this issue and the Wikipedia example above works well on my environment now. Can anyone test that?

**Comment by raviqqe** [comment]
@bensooter Don't you have a space after `100,` in the URL? Except that it works well with `muffet` for me.

**Comment by xyproto** [comment]
I also get errors for links with hashes. Example URL:

```
        ERROR   https://stackoverflow.com/questions/2951028/is-it-possible-to-include-inline-assembly-in-google-go-code/6535590#6535590 (ID #6535590 not found)
```

**Comment by raviqqe** [comment]
@xyproto I think it's actually because the URL is wrong. It should be `https://stackoverflow.com/questions/2951028/is-it-possible-to-include-inline-assembly-in-google-go-code/6535590#answer-6535590`.

**Comment by gtirloni** [comment]
@raviqqe tested with muffer 0.1.0 (f6b4cfc892c848e6f6d34b0ac8821b5a1f321be7) and I don't see the hash errors anymore. Thank you!

**Comment by raviqqe** [comment]
@xyproto It seems to be because StackOverflow's scripts handle that kind of fragments to navigate users to specific answers showing them with orange background highlights while the HTML has an element with the ID of `#answer-6535590`. If you want `muffet` to deal with that kind of problems maybe by using headless Chrome or something, please file another issue.

**Comment by xyproto** [comment]
@raviqqe I see, but Couldn't muffet have an option for just dropping everything after `#` when crawling pages for dead links? I think that would be useful.

**Comment by raviqqe** [comment]
@xyproto You idea about an option to ignore URL fragment parameters makes sense to me. Can you file another issue for it if you want maybe with some use cases?

I'm closing this issue as the original problem is fixed in the current version.
